export { default as Crypto } from './Crypto'
export { default as Home } from './Home'
export { default as Cryptodetail } from './Cryptodetail'
export { default as Exchange } from './Exchange'
export { default as News } from './News'
export { default as Navbar } from './Navbar'